FROM mongo
RUN apt-get update
RUN apt-get -y install netcat
COPY ["mongo-standalone-entrypoint.sh", "/root"]
COPY ["init.js", "/root"]
EXPOSE 32112
ENTRYPOINT ["/root/mongo-standalone-entrypoint.sh"]
