CREATE TABLE [dbo].[AuthData]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
	[UserId] UNIQUEIDENTIFIER NOT NULL, 
	[Username] NVARCHAR(20) NOT NULL, 
	[Password] VARCHAR(50) NOT NULL, 
	[Email] VARCHAR(320) NOT NULL
)
