FROM mongo
RUN apt-get update
RUN apt-get -y install netcat
RUN apt-get -y install cron
EXPOSE 32112
COPY ["scripts", "/scripts/"]
COPY update-cronjob /root
EXPOSE 32112
CMD [ "--replSet", "rs0", "--bind_ip_all" ]
COPY ["mongo-standalone-init.sh", "/docker-entrypoint-initdb.d/"]
COPY ["mongo-standalone-entry.sh", "/bin"]
RUN chmod +x "/bin/mongo-standalone-entry.sh"
ENTRYPOINT [ "mongo-standalone-entry.sh" ]
