FROM mongo
RUN apt-get update
RUN apt-get -y install netcat
RUN apt-get -y install cron
COPY ["mongo-standalone-entrypoint.sh", "/root"]
COPY ["init.js", "/root"]
COPY ["init-collections.js", "/root"]
EXPOSE 32112
RUN chmod +x /root/mongo-standalone-entrypoint.sh
COPY ["scripts", "/scripts/"]
COPY update-cronjob /root
EXPOSE 32112
ENTRYPOINT ["/root/mongo-standalone-entrypoint.sh"]
