FROM marekbf3/auctionhouse-sqlserver
COPY AuctionhouseDatabase.mdf AuctionhouseDatabase_log.ldf restore-AuctionhouseDatabase.sql ./
COPY sqlserver-entrypoint.sh /bin/sqlserver-entrypoint.sh
RUN chmod +x /bin/sqlserver-entrypoint.sh
ENTRYPOINT [ "sqlserver-entrypoint.sh" ]