# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- rewrite

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet tool install --global dotnet-ef'
- task: PowerShell@2
  displayName: 'Run command db build scripts'
  env:
    MSBuildBinPath: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\
  inputs:
    filePath: 'backend\src\Database\Command\Scripts\build\Build2.ps1'
    workingDirectory: 'backend\src\Database\Command\Scripts\build'
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Free P1(0ebcf8c7-bd19-44e1-9a1e-77cfc61def57)'
    AuthenticationType: 'server'
    ServerName: 'mptestfree.database.windows.net'
    DatabaseName: 'FreeTest'
    SqlUsername: 'sqladmin'
    SqlPassword: $(pass)
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: 'backend\src\Database\Command\AuctionhouseDatabase\bin\Debug\AuctionhouseDatabase.dacpac'
    IpDetectionMethod: 'AutoDetect'
