version: '3.4'

services:
  db-config1:
    image: ${DOCKER_REGISTRY-}pekalam/db-config1
    hostname: db-config1
    build:
      dockerfile: config/Dockerfile
      context: .
    command: ["--configsvr", "--replSet", "configRS", "--bind_ip_all", "--keyFile", "/data/mongocluster-keyfile"]
    volumes:
      - db-config1_data:/data/db
      - db-config1_config:/data/configdb
    secrets:
      - mongocluster-keyfile 
    depends_on:
      - db-node1
      - db-node2
      - db-node3
  mongodb:
    image: ${DOCKER_REGISTRY-}pekalam/mongodb
    hostname: mongodb
    build:
      dockerfile: mongos/Dockerfile
      context: .
    command: ["--wait-for", "db-config1:32112", "db-node1:32112", "db-node2:32112", "db-node3:32112", "--configdb", "configRS/db-config1:27019", "--bind_ip_all", "--keyFile=/data/mongocluster-keyfile"]
    ports:
      - "27017:27017"       
    volumes:
      - mongodb_mongos_data:/data/db
      - mongodb_mongos_config:/data/configdb
    secrets:
      - mongocluster-keyfile
      - mongouser-password
  db-node1:
    image: ${DOCKER_REGISTRY-}pekalam/db-node1
    hostname: db-node1
    build:
      dockerfile: shards/shard_db-node1/Dockerfile
      context: .
    command: [ "--bind_ip_all", "--replSet", "n1", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    volumes:
      - db-node1_data:/data/db
      - db-node1_config:/data/configdb
    secrets:
      - mongocluster-keyfile 
  db-node2:
    image: ${DOCKER_REGISTRY-}pekalam/db-node2
    hostname: db-node2
    build:
      dockerfile: shards/shard_db-node2/Dockerfile
      context: .
    command: [ "--bind_ip_all", "--replSet", "n2", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    volumes:
      - db-node2_data:/data/db
      - db-node2_config:/data/configdb
    secrets:
      - mongocluster-keyfile 
  db-node3:
    image: ${DOCKER_REGISTRY-}pekalam/db-node3
    hostname: db-node3
    build:
      dockerfile: shards/shard_db-node3/Dockerfile
      context: .
    command: [ "--bind_ip_all", "--replSet", "n3", "--shardsvr", "--keyFile=/data/mongocluster-keyfile" ]
    volumes:
      - db-node3_data:/data/db
      - db-node3_config:/data/configdb
    secrets:
      - mongocluster-keyfile 


volumes:
  db-config1_data:
  db-config1_config:
  db-node1_data:
  db-node1_config:
  db-node2_data:
  db-node2_config:
  db-node3_data:
  db-node3_config:
  mongodb_mongos_data:
  mongodb_mongos_config:

secrets:
  mongocluster-keyfile:
    external: true
  mongouser-password:
    external: true
