services:
  mongodb:
    image: ${DOCKER_REGISTRY-}pekalam/auctionhouse-mongodb-standalone
    ports:
      - '27017:27017'
    build:
      context: ../../MongoDb/standalone
      dockerfile: Dockerfile-mongo-standalone-replicaset
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb