FROM mongo
RUN apt-get update && apt-get -y install netcat
COPY ["common/wait-for", "/bin/wait-for"]
COPY ["shards/shard_{{shard_name}}/mongo-entrypoint.sh", "/root"]
RUN chmod +x /root/mongo-entrypoint.sh && chmod +x /bin/wait-for
COPY ["common", "/container-scripts/"]
EXPOSE 32112
COPY ["shards/shard_{{shard_name}}/scripts", "/scripts/"]
ENTRYPOINT ["/root/mongo-entrypoint.sh"]